
import Head from "next/head";
import { Carousel } from "react-bootstrap";






export default function index() {
 
  return (
    <>
   <Head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="path/to/font-awesome/css/font-awesome.min.css"
        />

        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
          integrity="sha512-FBGB6hBE4b+7P1VV0lo2UWf4z5AepD9/dvnnFAntY5iY5JmiLzqo9Q+L4tV8dRii2o4Mn0Bz7vT3XEaBUj02GQ=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
        <link
          rel="stylesheet"
          href="node_modules/@fortawesome/fontawesome-free/css/all.css"
        />
        <title>SchoolTransport.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <div className="carousel-container">
      <Carousel indicators={false} prevIcon={<PrevButton />} nextIcon={<NextButton />}>
        <Carousel.Item interval={10000}>
          <div className="carousel-item-content">
            <img
              className="carosalhome"
              src="/Images/bgone.jpg"
              alt="bg1"
            />
            <Carousel.Caption>
              <div className="container">
                <div className="col-sm-6">
              <h3>Child Transportation Made Simple</h3>
              <p>Paragraph 1</p>
              </div></div>
            </Carousel.Caption>
          </div>
        </Carousel.Item>
        <Carousel.Item interval={2000}>
          <div className="carousel-item-content">
            <img
              className="carosalhome"
              src="/Images/bgtwo.jpg"
              alt="bg2"
            />
            <Carousel.Caption>
              <h3>Heading 2</h3>
              <p>Paragraph 2</p>
            </Carousel.Caption>
          </div>
        </Carousel.Item>
        <Carousel.Item interval={5000}>
          <div className="carousel-item-content">
            <img
              className="carosalhome"
              src="/Images/bgthree.jpg"
              alt="bg3"
            />
            <Carousel.Caption>
              <h3>Heading 3</h3>
              <p>Paragraph 3</p>
            </Carousel.Caption>
          </div>
        </Carousel.Item>
      </Carousel>
    </div>
      </div>
    </>
  );
}
const PrevButton = (props) => (
  <button
     className="custom-carousel-button prev"
      onClick={props.onClick}
    ><i className="fa fa-angle-left"></i></button>
  );
  
   const NextButton = (props) => (
     <button
       className="custom-carousel-button next"
      onClick={props.onClick}
   ><i className="fa fa-angle-left"></i></button>
  );
  